"""
Alerts are DERIVED from live model outputs — not hardcoded. Every alert
below is generated by re-reading the current prospectivity grid / production
predictions and applying transparent threshold rules.
"""
from fastapi import APIRouter
from ..inference import prospectivity_engine, production_engine

router = APIRouter(prefix="/api/alerts", tags=["alerts"])


@router.get("")
def get_alerts():
    alerts = []

    # --- Exploration alerts from the prospectivity model ---
    grid = prospectivity_engine.grid_df
    high_zone = grid[grid.zone == "High"].sort_values("prospectivity_score", ascending=False)
    for _, row in high_zone.head(3).iterrows():
        alerts.append({
            "type": "exploration",
            "severity": "info",
            "title": "High-prospectivity zone identified",
            "message": (f"Cell at ({row['lat']:.3f}, {row['lon']:.3f}) scores "
                        f"{row['prospectivity_score']:.2f} prospectivity (confidence "
                        f"{row['confidence']:.2f}). Recommend field validation / sampling."),
            "lat": float(row["lat"]), "lon": float(row["lon"]),
        })

    # --- Operational alerts from the production/shortfall model ---
    for mine in production_engine.mines_list():
        pred = production_engine.predict(mine["mine_id"])
        if pred["risk_level"] in ("Medium", "High"):
            severity = "critical" if pred["risk_level"] == "High" else "warning"
            alerts.append({
                "type": "production",
                "severity": severity,
                "title": f"{pred['mine_name']}: {pred['risk_level']} shortfall risk",
                "message": (f"Predicted production {pred['predicted_production_tonnes']:.0f} t "
                            f"vs target {pred['planned_target_tonnes']:.0f} t "
                            f"(shortfall probability {pred['shortfall_probability']*100:.0f}%). "
                            f"Top driver: {pred['risk_drivers'][0]['label']}."),
                "mine_id": mine["mine_id"],
            })

    order = {"critical": 0, "warning": 1, "info": 2}
    alerts.sort(key=lambda a: order.get(a["severity"], 3))
    return {"count": len(alerts), "alerts": alerts}
